spring:
  h2:
    console:
      enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/basicspringmvcapp?useSSL=false&serverTimezone=Europe/Warsaw
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
